import type { TaskTemplate } from '../types'

export const SYSTEM_TEMPLATES: TaskTemplate[] = [
  {
    id: 'epf',
    name: 'EPF Monthly Submission',
    nameZh: '公积金月度呈报',
    category: 'monthly',
    deadlineRule: {
      type: 'day-of-month',
      dayOfMonth: 15,
      reminderDaysBefore: [7, 1],
    },
    governmentWebsite: {
      name: 'KWSP i-Akaun',
      url: 'https://majikan.kwsp.gov.my',
      loginUrl: 'https://majikan.kwsp.gov.my',
    },
    description: 'Monthly EPF (KWSP) employer contribution submission',
    isSystemDefault: true,
  },
  {
    id: 'socso',
    name: 'SOCSO Monthly Submission',
    nameZh: '社险月度呈报',
    category: 'monthly',
    deadlineRule: {
      type: 'day-of-month',
      dayOfMonth: 15,
      reminderDaysBefore: [7, 1],
    },
    governmentWebsite: {
      name: 'PERKESO ASSIST',
      url: 'https://assist.perkeso.gov.my',
      loginUrl: 'https://assist.perkeso.gov.my',
    },
    description: 'Monthly SOCSO (PERKESO) employer contribution submission',
    isSystemDefault: true,
  },
  {
    id: 'eis',
    name: 'EIS Monthly Submission',
    nameZh: '就业保险月度呈报',
    category: 'monthly',
    deadlineRule: {
      type: 'day-of-month',
      dayOfMonth: 15,
      reminderDaysBefore: [7, 1],
    },
    governmentWebsite: {
      name: 'PERKESO ASSIST',
      url: 'https://assist.perkeso.gov.my',
      loginUrl: 'https://assist.perkeso.gov.my',
    },
    description: 'Monthly EIS (Employment Insurance System) contribution submission',
    isSystemDefault: true,
  },
  {
    id: 'pcb',
    name: 'PCB Monthly Submission',
    nameZh: '月度税款扣缴呈报',
    category: 'monthly',
    deadlineRule: {
      type: 'day-of-month',
      dayOfMonth: 15,
      reminderDaysBefore: [7, 1],
    },
    governmentWebsite: {
      name: 'MyTax',
      url: 'https://mytax.hasil.gov.my',
      loginUrl: 'https://mytax.hasil.gov.my',
    },
    description: 'Monthly PCB (Potongan Cukai Berjadual) employee tax deduction submission',
    isSystemDefault: true,
  },
  {
    id: 'cp204',
    name: 'CP204 Monthly Instalment',
    nameZh: '企业税月度分期',
    category: 'monthly',
    deadlineRule: {
      type: 'day-of-month',
      dayOfMonth: 15,
      reminderDaysBefore: [7, 1],
    },
    governmentWebsite: {
      name: 'MyTax',
      url: 'https://mytax.hasil.gov.my',
      loginUrl: 'https://mytax.hasil.gov.my',
    },
    description: 'Monthly CP204 corporate tax instalment payment',
    isSystemDefault: true,
  },
  {
    id: 'einvoice',
    name: 'E-Invoice Consolidated Submission',
    nameZh: '合并电子发票月度呈报',
    category: 'monthly',
    deadlineRule: {
      type: 'day-of-month',
      dayOfMonth: 7,
      reminderDaysBefore: [3, 1],
    },
    governmentWebsite: {
      name: 'MyInvois',
      url: 'https://myinvois.hasil.gov.my',
      loginUrl: 'https://myinvois.hasil.gov.my',
    },
    description: 'Monthly consolidated e-invoice submission for previous month',
    isSystemDefault: true,
  },
  {
    id: 'sst',
    name: 'SST Bi-Monthly Return',
    nameZh: '销售与服务税双月申报',
    category: 'bi-monthly',
    deadlineRule: {
      type: 'day-of-month',
      dayOfMonth: 31,
      monthsOfYear: [3, 5, 7, 9, 11, 1],
      reminderDaysBefore: [14, 3],
    },
    governmentWebsite: {
      name: 'MySST',
      url: 'https://mysst.customs.gov.my',
      loginUrl: 'https://mysst.customs.gov.my',
    },
    description: 'Bi-monthly SST (Sales and Service Tax) return submission',
    isSystemDefault: true,
  },
  {
    id: 'borang-e',
    name: 'Borang E Submission',
    nameZh: '雇主年度申报表',
    category: 'yearly',
    deadlineRule: {
      type: 'day-of-year',
      dayOfYear: { month: 3, day: 31 },
      reminderDaysBefore: [30, 7],
    },
    governmentWebsite: {
      name: 'MyTax',
      url: 'https://mytax.hasil.gov.my',
      loginUrl: 'https://mytax.hasil.gov.my',
    },
    description: 'Annual employer return (Borang E) - due March 31',
    isSystemDefault: true,
  },
  {
    id: 'borang-ea',
    name: 'Borang EA Distribution',
    nameZh: '雇员年度收入报告',
    category: 'yearly',
    deadlineRule: {
      type: 'day-of-year',
      dayOfYear: { month: 2, day: 28 },
      reminderDaysBefore: [30, 7],
    },
    governmentWebsite: {
      name: 'MyTax',
      url: 'https://mytax.hasil.gov.my',
    },
    description: 'Annual employee income statement (Borang EA) - must be distributed by end of February',
    isSystemDefault: true,
  },
  {
    id: 'borang-c',
    name: 'Borang C Corporate Tax Return',
    nameZh: '企业所得税申报表',
    category: 'yearly',
    deadlineRule: {
      type: 'anniversary-based',
      reminderDaysBefore: [30, 7],
    },
    governmentWebsite: {
      name: 'MyTax',
      url: 'https://mytax.hasil.gov.my',
      loginUrl: 'https://mytax.hasil.gov.my',
    },
    description: 'Corporate income tax return (Borang C) - due 7 months after financial year end',
    isSystemDefault: true,
  },
  {
    id: 'borang-be',
    name: 'Borang BE Personal Tax Return',
    nameZh: '个人所得税申报表（雇员）',
    category: 'yearly',
    deadlineRule: {
      type: 'day-of-year',
      dayOfYear: { month: 4, day: 30 },
      reminderDaysBefore: [30, 7],
    },
    governmentWebsite: {
      name: 'MyTax',
      url: 'https://mytax.hasil.gov.my',
      loginUrl: 'https://mytax.hasil.gov.my',
    },
    description: 'Personal income tax return for employees (Borang BE) - due April 30',
    isSystemDefault: true,
  },
  {
    id: 'borang-b',
    name: 'Borang B Business Tax Return',
    nameZh: '个人所得税申报表（商业）',
    category: 'yearly',
    deadlineRule: {
      type: 'day-of-year',
      dayOfYear: { month: 6, day: 30 },
      reminderDaysBefore: [30, 7],
    },
    governmentWebsite: {
      name: 'MyTax',
      url: 'https://mytax.hasil.gov.my',
      loginUrl: 'https://mytax.hasil.gov.my',
    },
    description: 'Personal income tax return for business individuals (Borang B) - due June 30',
    isSystemDefault: true,
  },
  {
    id: 'ssm-annual',
    name: 'SSM Annual Return',
    nameZh: '公司注册局年度申报',
    category: 'yearly',
    deadlineRule: {
      type: 'anniversary-based',
      reminderDaysBefore: [30, 14, 3],
    },
    governmentWebsite: {
      name: 'SSM ezBiz',
      url: 'https://ezbiz.ssm.com.my',
      loginUrl: 'https://ezbiz.ssm.com.my',
    },
    description: 'Annual return to SSM (Companies Commission of Malaysia) - due on anniversary of incorporation',
    isSystemDefault: true,
  },
  {
    id: 'quit-rent',
    name: 'Quit Rent',
    nameZh: '地税',
    category: 'yearly',
    deadlineRule: {
      type: 'day-of-year',
      dayOfYear: { month: 5, day: 31 },
      reminderDaysBefore: [30, 7],
    },
    governmentWebsite: {
      name: 'PTG / ePBT',
      url: 'https://www.e-tanah.gov.my',
    },
    description: 'Annual quit rent (cukai tanah) payment to state land office',
    isSystemDefault: true,
  },
  {
    id: 'assessment-tax',
    name: 'Assessment Tax',
    nameZh: '门牌税',
    category: 'half-yearly',
    deadlineRule: {
      type: 'day-of-month',
      dayOfMonth: 28,
      monthsOfYear: [2, 8],
      reminderDaysBefore: [14, 3],
    },
    governmentWebsite: {
      name: 'PBT / Local Council',
      url: 'https://www.hasil.gov.my',
    },
    description: 'Half-yearly assessment tax (cukai pintu/cukai taksiran) payment to local council',
    isSystemDefault: true,
  },
]
